#!/usr/bin/env python3
"""Plot the reproducible subsonic runtime comparison.

Inputs:
    ``Table_subsonic_runtime.csv`` generated by
    ``plot_08_benchmark_subsonic_runtime.py``.
Outputs:
    PNG and PDF files selected with ``--output-stem``.
Provenance:
    The three rows and uncertainty intervals are read directly from the
    benchmark table. No timing or solver is rerun.
Command:
    python -m plots.scripts.pinn_subsonic.plot_subsonic_runtime

The historical image did not retain its one-off plotting script. This
reproducer preserves its data selection (loaded PINN, end-to-end PINN-seeded
GEP, and classical full mode), logarithmic scale, and quartile error bars.
Rendering metadata and exact font metrics may differ from the historical file.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_INPUT = (
    REPO_ROOT
    / "assets/pinn_subsonic/article/results_pinn/tables"
    / "Table_subsonic_runtime.csv"
)
DEFAULT_OUTPUT = (
    REPO_ROOT
    / "assets/pinn_subsonic/article/results_pinn/figures"
    / "Fig_subsonic_runtime"
)
METHODS = (
    "PINN full mode, loaded",
    "PINN-seeded GEP, end to end",
    "Classical full mode",
)
LABELS = ("PINN\nloaded", "PINN-seeded\nGEP", "Classical\nfull mode")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-csv", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-stem", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dpi", type=int, default=300)
    return parser.parse_args()


def build_figure(table: pd.DataFrame) -> plt.Figure:
    indexed = table.set_index("method")
    missing = [method for method in METHODS if method not in indexed.index]
    if missing:
        raise ValueError(f"Missing runtime rows: {missing}")
    selected = indexed.loc[list(METHODS)]

    medians = selected["median_ms"].to_numpy(dtype=float)
    lower = medians - selected["q1_ms"].to_numpy(dtype=float)
    upper = selected["q3_ms"].to_numpy(dtype=float) - medians

    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    positions = np.arange(len(METHODS))
    ax.bar(
        positions,
        medians,
        yerr=np.vstack((lower, upper)),
        capsize=4,
        color="#1f77b4",
        alpha=0.95,
    )
    ax.set_yscale("log")
    ax.set_xticks(positions, LABELS)
    ax.set_ylabel("Median latency [ms]")
    ax.set_title("Representative-point inference latency")
    ax.grid(axis="y", which="both", alpha=0.28)
    fig.tight_layout()
    return fig


def main() -> None:
    args = parse_args()
    table = pd.read_csv(args.input_csv)
    args.output_stem.parent.mkdir(parents=True, exist_ok=True)
    figure = build_figure(table)
    figure.savefig(args.output_stem.with_suffix(".png"), dpi=args.dpi)
    figure.savefig(args.output_stem.with_suffix(".pdf"))
    plt.close(figure)


if __name__ == "__main__":
    main()
